// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BinLiquidity = {
	bin_id: number;
	price: number;
	base_amount: number;
	quote_amount: number;
};
