// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BondingView = {
	completion_pct: number | null;
	stage: string | null;
	virtual_sol_reserves: number;
};
