// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundleCluster = {
	cluster_key: string;
	kind: string;
	wallets: Array<string>;
	combined_sol: number;
	combined_tokens: number;
	pct_of_early_sol: number;
};
