// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CachedPosition = {
	position_address: string;
	pool_address: string;
	lower_bin_id: number;
	upper_bin_id: number;
};
