// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Candle = {
	t_ms: number;
	open: number;
	high: number;
	low: number;
	close: number;
	volume_usd: number;
	volume_sol: number;
	txns: number;
	buys: bigint;
	sells: number;
	traders: bigint;
};
