// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CtoFlagRow = {
	mint: string;
	dev_balance_zeroed: boolean;
	dev_zeroed_at_ms: number;
	socials_changed_after: boolean;
	socials_changed_at_ms: number;
	is_cto: boolean;
};
