// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DepositSplit = {
	deposits_usd: number | null;
	withdrawals_usd: number | null;
	net_pct: number | null;
};
