// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DevTokenEntry } from "./DevTokenEntry";

export type DevTokensResponse = {
	creator: string;
	total_tokens: number;
	migrated: Array<DevTokenEntry>;
	unmigrated: Array<DevTokenEntry>;
};
