// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DevTokenEntry = {
	mint: string;
	symbol: string | null;
	name: string | null;
	market_cap_usd: number | null;
	liquidity_usd: number | null;
	stage: string | null;
	decimals: number | null;
	created_ms: number;
	token_program: string | null;
	mint_authority_disabled: boolean | null;
	freeze_authority_disabled: boolean | null;
	has_permanent_delegate: boolean | null;
	has_transfer_hook: boolean | null;
};
