export type Dex =
  | "meteora_dlmm"
  | "meteora_dbc"
  | "meteora_damm2 "
  | "pumpswap"
  | "pumpfun"
  | "raydium_clmm"
  | "raydium_cpmm"
  | "raydium_launchpad"
  | "orca_whirlpool"
  | "phoenix"
  | "zerofi"
  | "stabble_stable"
  | "stable_weighted"
  | "gavel"
  | "bonkswap"
  | "saros"
  | "fluxbeam"
  | "lifinity_v2"
  | "obric_v2";
