// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EarlyBuyerRow = {
	wallet: string;
	first_slot: number;
	sol_spent: number;
	tokens_bought: number;
	funder: string;
	sig_count: number;
};
