// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeeSummaryRow = {
	total_fee_sol: number;
	avg_fee_bps: number;
	total_creator_fee_sol: number;
	avg_creator_fee_bps: number;
	total_cashback_sol: number;
	trades_with_fee: number;
};
