// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HolderSnapshotRow = {
	holder_count: number;
	top10_holder_pct: number;
	dev_balance: number;
	dev_holder_pct: number;
	last_update_ms: number;
};
