// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InsiderRow } from "./InsiderRow";

export type InsidersResponse = {
	creator_wallet: string;
	creator_funder: string;
	insider_count: number;
	insiders: Array<InsiderRow>;
};
