// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InsiderRow = {
  wallet: string;
  relation: string;
  sol_spent: number;
  tokens_bought: number;
};
