// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Redis hashes are inherently string-valued. Coerce numeric-looking
 * values to real JSON numbers so `live`/`bonding` match the typed
 * ClickHouse-backed `holders`/`social` fields in the same response
 * (frontend was getting "0" (string) here vs 0 (number) there for the
 * same conceptual field -- confirmed bug via oni's integration report).
 * Non-numeric strings (wallet/pool addresses, mints) never parse as a
 * number, so they safely fall through to Value::String unchanged.
 */
export type LiveView = {
	price_usd: number | null;
	volume_1h_usd: number | null;
	txns_1m: number;
	updated_at: number | null;
};
