// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LpEvent = {
	pool_address: string;
	mint: string;
	is_deposit: number;
	token_amount: number;
	block_time: number;
};
