// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LpCalendarDay } from "./LpCalendarDay";
import type { LpPosition } from "./LpPosition";

export type LpPortfolioResponse = {
	wallet: string;
	lp_positions: Array<LpPosition>;
	total_value_usd: number;
	calendar: Array<LpCalendarDay>;
};
