// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LpPosition = {
  pool_address: string;
  mint: string;
  symbol: string | null;
  deposited: number;
  withdrawn: number;
  net_amount: number;
  current_value_usd: number | null;
  is_open: boolean;
};
