// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PoolInfo = {
	pool_address: string;
	dex: string;
	token_a: string;
	token_b: string;
	liquidity_usd: number;
};
