// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PoolsQuery = {
  dex: string | null;
  query: string | null;
  min_bin_step: number | null;
  max_bin_step: number | null;
  min_tick_spacing: number | null;
  max_tick_spacing: number | null;
  min_volume_1h: number | null;
  sort: string | null;
  order: string | null;
  limit: number | null;
  offset: number | null;
};
