// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RugcheckResponse = {
	mint: string;
	cached: boolean;
	fetched_at_ms: number;
	upstream_status: number;
	report: JsonValue;
};
