// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SafetyView = {
  token_program: string;
  mint_authority_renounced: number;
  freeze_authority_renounced: number;
  has_permanent_delegate: number;
  has_transfer_hook: number;
  has_transfer_fee: number;
  non_transferable: number;
  has_default_account_state_ext: number;
  checked_at_ms: number;
};
