// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScreenerQuery = {
	query: string | null;
	launchpad: string | null;
	stage: string | null;
	min_pct: number | null;
	max_pct: number | null;
	min_age_sec: number | null;
	max_age_sec: number | null;
	min_mcap: number | null;
	max_mcap: number | null;
	min_holders: number | null;
	max_holders: number | null;
	min_top10_pct: number | null;
	max_top10_pct: number | null;
	min_dev_pct: number | null;
	max_dev_pct: number | null;
	min_liquidity: number | null;
	min_volume_1h: number | null;
	has_socials: boolean | null;
	dex_boost: boolean | null;
	dex_paid: boolean | null;
	dev_sold: boolean | null;
	mint_auth_disabled: boolean | null;
	freeze_auth_disabled: boolean | null;
	include_incomplete: boolean | null;
	sort: string | null;
	order: string | null;
	limit: number | null;
	offset: number | null;
};
