// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SniperRow = {
  wallet: string;
  first_buy_slot_delta: number;
  buys_in_window: bigint;
  tokens_bought: number;
  sol_spent: number;
};
