// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SniperRow } from "./SniperRow";

export type SnipersResponse = {
	creation_slot: number;
	window_slots: bigint;
	sniper_count: number;
	snipers: Array<SniperRow>;
};
