// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SocialMetaRow = {
	website_url: string;
	twitter_handle: string;
	twitter_url: string;
	telegram_url: string;
	boosts_active: number;
	has_paid_order: number;
	dexscreener_price_usd: number;
	dexscreener_liquidity_usd: number;
	dexscreener_fdv_usd: number;
	dexscreener_market_cap_usd: number;
	last_update_ms: number;
};
