// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SurgeQuery = {
	include_incomplete: boolean | null;
	direction: string | null;
	min_surge_pct: number | null;
	sort: string | null;
	order: string | null;
	limit: number | null;
	offset: number | null;
};
