// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimeframeMetrics = {
  volume_usd: number;
  trade_count: number;
  buy: bigint;
  sell: number;
  unique_wallet: bigint;
  price_change_percent: number;
  volume_buy_usd: number | null;
  volume_sell_usd: number | null;
};
