// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenPosition = {
  mint: string;
  symbol: string | null;
  bought: number;
  sold: number;
  remaining: number;
  realized_pnl_usd: number;
  unrealized_pnl_usd: number | null;
  avg_buy_price_usd: number;
  current_price_usd: number | null;
  first_trade_unix: number;
  last_trade_unix: bigint;
  holding_duration_secs: number;
};
