// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarDay } from "./CalendarDay";
import type { TokenPosition } from "./TokenPosition";

export type TokenPortfolioResponse = {
  wallet: string;
  total_wallet_worth_usd: number;
  total_invested_usd: number;
  total_pnl_usd: number;
  realized_pnl_usd: number;
  total_transactions: number;
  tokens: Array<TokenPosition>;
  calendar: Array<CalendarDay>;
};
