// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FeeSummary } from "./FeeSummary";
import type { WindowStats } from "./WindowStats";

export type TokenStats = {
	created_at_ms: number;
	age_seconds: bigint | null;
	last_price_usd: number;
	windows: { [key in string]?: WindowStats };
	fees: FeeSummary;
};
