import type { WalletTag } from "./WalletTag";

export type TokenTopTrader = {
  pnl_pct: number;
  holding: number;
  decimals: number;
  bought: number;
  sold: number;
  transfer_net: number;
  cost_usd: number;
  value_usd: number;
  invested_usd: number;
  proceeds_usd: number;
  realized_usd: number;
  unrealized_usd: number;
  avg_buy_usd: number;
  avg_sell_usd: number;
  buys: number;
  sells: number;
  first_trade: number;
  last_trade: number;
  holding_duration_secs: number;
  remaining_ui: number;
  pnl_usd: number;
  wallet: string;
  total_usd: number;
  tags: WalletTag[];
  last_active: number;
  avg_buy_mcap_usd: number;
  avg_sell_mcap_usd: number;
  win_rate_7d_pct: number;
  avg_duration_7d_secs: number;
  pnl_7d_usd: number;
  sol_balance: number;
  first_funder: string | null;
  first_funded_amount: number;
  first_funded_slot: number;
  first_funded_time: number;
};
