// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TokenMetaEntry = {
  mint: string;
  name: string;
  symbol: string;
  uri: string;
};
