// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GET /token/:mint/trades?limit=50&offset=0&side=buy|sell
 * Per-token trade feed: wallet, side, amounts, price, time.
 * Ordered by slot DESC (matches the (mint, slot, signature) sort key -> fast,
 * contiguous read; slot is monotonic so this is chronological newest-first).
 * GET /token/:mint/trades/stream — live SSE feed of new trades for this token.
 * Subscribes to the per-mint NATS subject (solana.trades.*.<mint>) and forwards each
 * TradeEvent to the browser as it lands. Pair with GET /token/:mint/trades for the
 * initial backlog; this stream provides the live tail.
 */
export type TopTrader = {
  wallet: string;
  volume_lamports: number;
  amount_bought_sol: number;
  amount_sold_sol: number;
  avg_buy_mcap: number;
  avg_sell_mcap: number;
  realized_pnl_sol: number;
  realized_pnl_usd: number;
  unrealized_pnl_sol: number;
  unrealized_pnl_usd: number;
  tokens_held: number;
  buys: bigint;
  sells: number;
  trades: bigint;
};
