// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TradeRow = {
	wallet: string;
	side: string;
	sol_amount: number;
	token_amount: bigint;
	price_usd: number;
	block_time: number;
};
