// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrendingEntry = {
  mint: string;
  score: number;
  token_name: string | null;
  token_symbol: string | null;
  image_url: string | null;
};
