// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrendingRow = {
  mint: string;
  volume_usd: number;
  volume_sol: number;
  swaps: number;
  traders: bigint;
  price_change_pct: number;
  trending_score: number;
};
