// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrenchesRow = {
	mint: string;
	launchpad: string;
	completion_pct: number;
	stage: string;
	virtual_sol_reserves: number;
	last_update_ms: bigint;
	token_name: string | null;
	token_symbol: string | null;
	image_url: string | null;
};
