// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TvlSplit = {
  base_usd: number | null;
  base_pct: number | null;
  quote_usd: number | null;
  quote_pct: number | null;
};
