// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletFundingView = {
	wallet: string;
	funder: string;
	funding_sol: number;
	funding_slot: number;
	sig_count: number;
	first_seen_slot: number;
	walked_at_ms: bigint;
};
