// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalletTagRow = {
  tag: string;
  note: string;
  added_by: string;
  added_at_ms: number;
};
