// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowStats = {
  swaps: number;
  buys: bigint;
  sells: number;
  traders: bigint;
  volume_usd: number;
  volume_sol: number;
  price_change_pct: number;
  avg_vol_per_min_usd: number;
  open: number;
  high: number;
  low: number;
  close: number;
};
