// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WindowStatsRow = {
	open: number;
	close: number;
	high: number;
	low: number;
	volume_usd: number;
	volume_sol: number;
	swaps: number;
	buys: bigint;
	sells: number;
	traders: bigint;
};
